changelog:
  exclude:
    labels:
      - "duplicate"
      - "question"
      - "invalid"
      - "wontfix"
  categories:
    - title: "**💥 Breaking:**"
      labels:
        - "bc break"
    - title: "**🍰 Enhancements:**"
      labels:
        - "enhancement"
    - title: "**🐞 Bugs:**"
      labels:
        - "bug"
    - title: "**💀 Deprecated:**"
      labels:
        - "deprecated"
    - title: "**🗑 Removed:**"
      labels:
        - "removed"
    - title: "**🛡 Security:**"
      labels:
        - "security"
    - title: "**🕸 Dependencies:**"
      labels:
        - "dependencies"
    - title: "**🧹 Maintenance:**"
      labels:
        - "maintenance"
    - title: "**📦 Documentation:**"
      labels:
        - "documentation"
    - title: "**📦 new Useragents:**"
      labels:
        - "new useragents"
    - title: "** Other Changes **"
      labels:
        - "*"
