<?php

/**
 * This file is part of the browscap-helper package.
 *
 * Copyright (c) 2015-2025, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace BrowscapHelper\Traits;

use UnexpectedValueException;

use function array_filter;
use function array_map;
use function in_array;
use function is_string;
use function sprintf;
use function trim;

use const ARRAY_FILTER_USE_BOTH;
use const ARRAY_FILTER_USE_KEY;

trait FilterHeaderTrait
{
    /**
     * @param array<string, string> $headers
     *
     * @return array<non-empty-string, non-empty-string>
     *
     * @throws UnexpectedValueException
     */
    private function filterHeaders(array $headers): array
    {
        $headers = array_filter(
            $headers,
            static fn (mixed $header): bool => is_string($header),
        );

        $headers = array_filter(
            $headers,
            /** @throws UnexpectedValueException */
            static function (string $header): bool {
                $allowedHeaders = [
                    'user-agent',
                    'ua-os',
                    'x-requested-with',
                    'baidu-flyflow',
                    'x-device-user-agent',
                    'device-stock-ua',
                    'x-skyfire-version',
                    'x-skyfire-phone',
                    'x-bluecoat-via',
                    'x-operamini-phone-ua',
                    'x-operamini-phone',
                    'x-ucbrowser-ua',
                    'x-ucbrowser-device-ua',
                    'x-ucbrowser-device',
                    'x-ucbrowser-phone-ua',
                    'x-ucbrowser-phone',
                    'x-original-user-agent',
                    'x-bolt-phone-ua',
                    'x-mobile-ua',
                    'baidu-flyflow',
                    'x-wap-profile',
                    'x-puffin-ua',
                    'x-mobile-gateway',
                    'x-nb-content',
                    'sec-ch-ua',
                    'sec-ch-ua-arch',
                    'sec-ch-ua-bitness',
                    'sec-ch-ua-full-version',
                    'sec-ch-ua-full-version-list',
                    'sec-ch-ua-mobile',
                    'sec-ch-ua-model',
                    'sec-ch-ua-platform',
                    'sec-ch-ua-platform-version',
                    'ua-cpu',
                    'sec-ch-prefers-color-scheme',
                    'sec-ch-device-memory',
                    'sec-ch-dpr',
                    'sec-ch-viewport-width',
                    'device-memory',
                    'downlink',
                    'dpr',
                    'ect',
                    'rtt',
                    'viewport-width',
                    'x-client',
                    'screenwidth',
                    'http-x-requested-with',
                    'sapphire-devicetype',
                    'sapphire-osversion',
                    'x-application-type',
                    'x-client-version',
                    'sec-ch-viewport-height',
                    'sec-ch-prefers-reduced-motion',
                    'useragent',
                    'service-name',
                    'sec-ch-ua-wow64',
                    'x-application',
                    'sec-ch-prefers-reduced-transparency',
                    'x-crawled-by',
                    'sec-ch-ua-form-factors',
                    'viewport-height',
                ];

                if (in_array($header, $allowedHeaders, true)) {
                    return true;
                }

                $forbiddenHeaders = [
                    'x-operamini-features',
                    'q-ua',
                    'x-mobileiron-securebrowser-managed-by',
                    'ua-color',
                    'x-nokia-device-type',
                    'sec-fetch-site',
                    'sec-fetch-mode',
                    'sec-fetch-dest',
                    'sec-fetch-user',
                    'dnt',
                    'save-data',
                    'if-modified-since',
                    'sentry-trace',
                    'traceparent',
                    'x-b3-flags',
                    'x-b3-spanid',
                    'x-b3-sampled',
                    'x-b3-traceid',
                    'sec-gpc',
                    'x-fb-crawlerbot',
                    'ms-cv',
                    'x-bufferbot',
                    'x-icm-a',
                    'request-id',
                    'request-context',
                    'cf-worker',
                    'cf-ew-via',
                    'x-b3-parentspanid',
                    'purpose',
                    'cf-visitor',
                    'cf-ray',
                    'cf-ipcountry',
                    'cf-connecting-ip',
                    'cdn-loop',
                    'x-surfly-sessionid',
                    'client-ip',
                    'x-edge-shopping-flag',
                    'x-client-data',
                    'baggage',
                    'priority',
                    'x-enrichmentstatus',
                    'x-zm-b3',
                    'want-digest',
                    'newrelic',
                    'x-istio-attributes',
                    'x-real-host',
                    'x-envoy-peer-metadata-id',
                    'x-envoy-peer-metadata',
                    'x-envoy-decorator-operation',
                    'x-envoy-attempt-count',
                    'llf-override-control',
                    'if-none-match',
                    'x-request-id',
                    'x-openai-traffic-source',
                    'x-openai-originator-env',
                    'x-openai-originator',
                    'tracestate',
                    'x-datadog-origin',
                    'x-datadog-parent-id',
                    'x-datadog-sampling-priority',
                    'x-datadog-tags',
                    'x-datadog-trace-id',
                    'x-envoy-expected-rq-timeout-ms',
                    'x-openai-internal-caller',
                    'accept-charset',
                    'refresh-cache',
                    'content-type',
                    'content-length',
                    'range',
                    'x-icm',
                    'x-client-ip',
                    'x-real-ip',
                    'x-myref',
                    'propagated-cipp-context',
                    'access-control-allow-origin',
                    'access-control-allow-methods',
                    'access-control-max-age',
                    'access-control-allow-headers',
                    'x-ps-ver',
                    'prefer',
                    'content-language',
                    'elastic-apm-traceparent',
                    'cp-extension-installed',
                    'category',
                    'x-imforwards',
                    'access-control-request-headers',
                    'access-control-request-method',
                    'authentication',
                    'location',
                    'x-api-version',
                    'x-csrf-token',
                    'x-druid-comment',
                    'x-origin',
                    'x-rewrite-url',
                    'x-remote-ip',
                    'x-forwarded',
                    'x-forwarded-for-original',
                    'x-original-host',
                    'x-original-url',
                    'x-originally-forwarded-for',
                    'x-originating-ip',
                    'x-original-remote-addr',
                    'x-iws-via',
                    'x-newrelic-id',
                    'x-newrelic-transaction',
                    'x-miorigin',
                    'thumbhight',
                    'totaltimeout',
                    'thumbquality',
                    'thumbwidth',
                    'x-cloud-trace-context',
                    'x-p2p-peerdist',
                    'x-p2p-peerdistex',
                    'x-office-major-version',
                    'x-ms-cookieuri-requested',
                    'x-featureversion',
                    'accept-auth',
                    'x-forward-for',
                    'x-chrome-offline',
                    'x-hubspot-timeout-millis',
                    'x-trace',
                    'x-hubspot-correlation-id',
                    'x-hubspot-requesting-chain-bin',
                    'x-hubspot-client-ip',
                    'x-octogate-auth',
                    'surrogate-capability',
                    'amp-cache-transform',
                    'propagated-context-graph-ids',
                    'propagated-request-id',
                    'forwarded',
                    'x-purpose',
                    'x-proxyuser-ip',
                    'sec-purpose',
                    'uber-trace-id',
                    'correlation-context',
                    'mime-version',
                    'content-transfer-encoding',
                    'referrer',
                    'x-slg-gls',
                    'depth',
                    'translate',
                    'max-forwards',
                    'x-ldebug',
                    'date',
                    'sapphire-configuration',
                    'sapphire-apiversion',
                    'sapphire-market',
                    'x-search-clientid',
                    'x-search-location',
                    'cacheoptions',
                    'p-mi-om',
                    'x-country',
                    'propagated-ipf-logger-context-v2',
                    'postman-token',
                    'x-slg-spool',
                    'x-proxymesh-timeout',
                    'x-gls-slg',
                    'x-sl-chef-ip',
                    'x-sl-job-id',
                    'x-sl-tunnel-id',
                    'x-chrome-uma-enabled',
                    'x-chrome-connected',
                    'x-clacks-overhead',
                    'x-spool-gls',
                    'x-spool-slg',
                    'x-gls-spool',
                    'x-ms-applicationguard-initiated',
                    'y-rid',
                    'content-length-proc',
                    'progress-proc',
                    'allow-redirections',
                    'encoding',
                    'max-redirects',
                    'open-timeout',
                    'read-timeout',
                    'ssl-verify-mode',
                    'x-aggregate-auth',
                    'x-anyconnect-platform',
                    'x-transcend-version',
                    'preferanonymous',
                    'ns-client-ip',
                    'ns-client-port',
                    'x-client-scheme',
                    'x5-uuid',
                    'sw8',
                    'sw8-x',
                    'a-im',
                    'social-go-service',
                    'x-apple-store-front',
                    'x-apple-tz',
                    'x-microsoftajax',
                    'webdev',
                    'llf-cache-control',
                    'llf-connection-reqpriority',
                    '',
                    'x-nimbus-clientid',
                    'x-amzn-trace-id',
                    'x-unique-id',
                    'if-unmodified-since',
                    'https',
                    'accept-ranges',
                    'x-ps3-browser',
                    'x-pocket-parser',
                    'expect',
                    'lcp',
                    'content-charset',
                    'browse-start',
                    'trace',
                    'x-ms-request-id',
                    'x-ms-request-root-id',
                    'dcp-akamai-token',
                    'authority',
                    'accept-languagae',
                    'q-ua2',
                    'moolah-tag',
                    'surfly-forwarded',
                    'x-ss-proto',
                    'accesstoken',
                    'ping-from',
                    'ping-to',
                    'x-li-calltree-request-id',
                    'x-li-r2-w-ic-1',
                    'x-li-r2-w-ic-1-servicecalltracedata',
                    'shenma-host',
                    'shenma-ip',
                    'ccept-encoding',
                    'propagated-observability-flags',
                    'x-operamini-route',
                    'expires',
                    'startpage-extension',
                    'content',
                    'token',
                    'x-msgetweburl',
                    'ignorecookieauthentication',
                    'x-instana-l',
                    'x-instana-s',
                    'x-instana-t',
                    'sdc-uuid',
                    'contact',
                    'profile',
                    'true-client-ip',
                    'x-host',
                    'x-http-host-override',
                    'x-li-r2-w-ic-1-applicationfailout',
                    'x-li-r2-w-ic-1-countrycode',
                    'x-li-r2-w-ic-1-mik',
                    'x-li-r2-w-ic-1-multicologenerationkey',
                    'x-li-r2-w-ic-1-traffic-tiering',
                    'x-li-r2-w-ic-1-user-request-host',
                    'x-li-r2-w-ic-2',
                    'x-li-r2-w-ic-2-xlitrack',
                    'apikey',
                    'x-bd-traceid',
                    'x-from-h3-trnet',
                    'accept-endcoding',
                    'reverse-via',
                    'x-varnish',
                    'x-from',
                    'x-tp-category',
                    'b3',
                    'x-wpt-ok',
                    'x-api-key',
                    'lastredirect',
                    'x-hide-searchbox',
                    'x-sidebar-search',
                    'x-wcpay-platform-checkout-user',
                    'x-predictor',
                    'http-forwarded-for',
                    'http-remote-addr',
                    'http-x-forwarded',
                    'http-x-forwarded-for',
                    'http-x-remote-addr',
                    'remote-addr',
                    'x-remote-addr',
                    'x-bd-quic',
                    'x-bdboxapp-netengine',
                    'x-turbonet-info',
                    'x-native-host',
                    'bdpparallelload',
                    'method',
                    'insecure-flag',
                    'brands',
                    'fullversionlist',
                    'mobile',
                    'platform',
                    'platformversion',
                    'uafullversion',
                    'wow64',
                    'architecture',
                    'ijj2ioj073',
                    't8emugbl56',
                    'x-forwarded-port',
                    'x-forwarded-prefix',
                    'x-forwarded-protocol',
                    'x-forwarded-scheme',
                    'x-forwarded-ssl',
                    'x-original-port',
                    'x-original-proto',
                    'x-original-protocol',
                    'x-original-server',
                    'x-original-ssl',
                    'searchpagetype',
                    'statusbar-height',
                    'zeus-pagetype',
                    'content-dir',
                    'cache',
                    'content-encoding',
                    'fcm-token',
                    'bdt',
                    'referrer-policy',
                    'tth-endproxy',
                    'model',
                    'x-openai-host-hash',
                    'content-disposition',
                    'x-requester',
                    'redirect-status',
                    'oai-host-hash',
                    'sec-websocket-key',
                    'sec-websocket-version',
                    'x-amzn-apigateway-api-id',
                    'x-my-x-amzn-trace-id',
                    'x-my-x-forwarded-for',
                    'http-upgrade-insecure-requests',
                    'no-sso',
                    'think-lang',
                    'iv-user',
                    'password',
                    'x-auth-level',
                    'headers',
                    'x-scanned-by',
                    'x-goog-authuser',
                    'client',
                    'cdn-server-port',
                    'cdn-src-ip',
                    'x-cdn-src-port',
                    'x-http-protocol',
                    'x-via',
                    'x-ws-request-id',
                    'id',
                    'x',
                    'xdoim',
                    'test',
                    'x-citrix-am-credentialtypes',
                    'x-citrix-am-labeltypes',
                    'x-citrix-isusinghttps',
                    'fly-client-ip',
                    'fly-forwarded-port',
                    'fly-forwarded-proto',
                    'fly-forwarded-ssl',
                    'fly-region',
                    'fly-request-id',
                    'fly-traceparent',
                    'x-request-start',
                    'x-swg-via',
                    'sec-ms-gec',
                    'sec-ms-gec-version',
                    'document',
                    'server-timing',
                    'via',
                    'from',
                    'origin',
                ];

                if (in_array($header, $forbiddenHeaders, true)) {
                    return false;
                }

                throw new UnexpectedValueException(sprintf('invalid header: "%s"', $header));
            },
            ARRAY_FILTER_USE_KEY,
        );

        $headers = array_map(
            static fn (string $header) => trim($header),
            $headers,
        );

        return array_filter(
            $headers,
            static fn (string $header, string $key): bool => $header !== '' && $key !== '',
            ARRAY_FILTER_USE_BOTH,
        );
    }
}
